name: Unity Export unitypackage

on:
  push:
    tags:
      - 'v*'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build UnityPackage
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set version
      id: version
      run: |
        VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
        echo ::set-output name=version::$VERSION
        echo ::set-output name=filedir::QuichePantiePatchEditor_$VERSION
        echo ::set-output name=filename::QuichePantiePatchEditor_$VERSION.unitypackage
        echo "Version $VERSION"

    - name: Build project
      uses: game-ci/unity-builder@v1.5
      with:
        unityVersion: 2018.4.20f1
        buildMethod: UnityPackageExporter.Export

    - name: Add version to Package
      run: mv QuichePantiePatchEditor.unitypackage ${{ steps.version.outputs.filename }}
    
    - name: Zip UnityPackage
      run: |
        DIR=$(echo ${{ steps.version.outputs.filedir }})
        mkdir $DIR
        cp -f ${{ steps.version.outputs.filename }} $DIR
        zip -r $DIR.zip $DIR

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release Quiche Pantie Patch Editor ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset UnityPackage
      id: upload-release-asset-unitypackage
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.version.outputs.filename }}
        asset_name: ${{ steps.version.outputs.filename }}
        asset_content_type: application/zip
    
    - name: Upload Release Asset Zip
      id: upload-release-asset-zip
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.version.outputs.filedir }}.zip
        asset_name: ${{ steps.version.outputs.filedir }}.zip
        asset_content_type: application/zip
        